### ISSUE TITLE
Reset the World

### ISSUE THREAD

**Issue by thorwolpert** [bcgov/business-ar#88]
Notebook to reset test data:
- [x] in the business-ar database (#180)
- [x] in the colin database (#181)
- [x] in sbc-auth (remove test accounts, users, assignments) (#182)
- [ ] update the test spreadsheet (#183)

future reset
- [ ] in the business database (OCP based) (#184)
